### ISSUE TITLE
Resume autorotation after delay

### ISSUE THREAD

**Issue by paulmasson** [ladybug-tools/spider-covid-19-viz-3d#13]
@theo-armour this always one of the things you tell me to do. Easy to implement.

Should also perhaps remove the `reset view` and `rotate` buttons, as well as improve the look of the `global statistics` button. These are things I could do, but want to get our work flow synced first, so maybe you should just address this.

**Comment by theo-armour** [comment]
yes yes yes.  many ideas about collaboration. let me got more of today's to
do list done. then we talk. late this afternoon!

thanks for the messaging/marketing effort.

I think the main thing about me and merging and collaborating is that

1. somehow I really need to see and run the script before and while
checking the merge.
2. I want to do this without having download or run a batch file. I just
want to click a link in a readme and see it - just like the way I check my
own code.

More - and your thoughts on this - later...

**Comment by paulmasson** [comment]
@theo-armour looking at how you turn off rotation, in order to resume you'll need a global timer variable, then a single function that removes that timer, sets `autoRotate` to false then sets a timeout on the timer to return it to true.

**Comment by theo-armour** [comment]
@paulmasson 

Sounds good, but not doing that today. I've done enough coding for the day.

**Comment by paulmasson** [comment]
Fixed in bafb25d3d28619ce4ebf713920a7631d1f055eec
