### ISSUE TITLE
Display of sidebar title in Firefox

### ISSUE THREAD

**Issue by paulmasson** [ladybug-tools/spider-covid-19-viz-3d#19]
@theo-armour the version number is too large in Firefox to fit inside the sidebar width and so always starts on another line. This occurs regardless of what setting is used for word wrap in the enclosing `<h2>` element or whether all of the text is concatenated inside the `<a>` element. As a result the title looks simply awful in Firefox. Safari and Chrome do not have this problem.

Options are to replace `<h2>` with `<p>` or widen the sidebar a bit.

**Comment by theo-armour** [comment]
@paulmasson 

sidebar has been widened in dev

**Comment by paulmasson** [comment]
Fixed in dev with bdb1fc9. Opened #21 to fix in stable.
