### ISSUE TITLE
Data attribution

### ISSUE THREAD

**Issue by loleg** [ladybug-tools/spider-covid-19-viz-3d#3]
It is quite important to link to your sources, and at the moment I'm not seeing that in the menu or legend. If you are doing any transformation to the data, then even better than a direct link would be to a Data Package that is used for this dataviz, which describes the changes made to the schema or content.

**Comment by theo-armour** [comment]
@loleg 
Agree on all points.

It's starting to happen in the readme

https://www.ladybug.tools/spider-covid-19-viz-3d/app/

but much more can be done.

**Comment by theo-armour** [comment]
Also in the ?? pop-up in the left menu of the app
